### ISSUE TITLE
Exclude `client_secret_*` values from `token_endpoint_auth_method`

### ISSUE THREAD

**Issue by aaronpk** [aaronpk/draft-parecki-oauth-client-id-metadata-document#7]
We should prohibit any `client_secret_*` values in the `token_endpoint_auth_method` for client metadata. 

https://www.rfc-editor.org/rfc/rfc7591#section-2

**Comment by ThisIsMissEm** [comment]
that's what Solid OIDC does by mandating that `token_endpoint_auth_method` must be `none` — are there any other `token_endpoint_auth_method`s that exist besides those for client credentials?
